Upgrade to sailor 2.6.18
elasticio/xml-component pull request #42
Opened 2020-10-26 14:12 UTC by denyshld

Remove sensitive logs

2020-10-26 14:36 UTC, shulkaolka requested changes

2020-10-26 14:36 UTC, shulkaolka commented on lib/actions/attachmentToJson.js
> +    self.logger.debug('Provided is not .xml file: ', fileName);
```suggestion
    self.logger.debug('Provided fileName is not .xml file');
```

2020-10-26 14:36 UTC, shulkaolka commented on lib/actions/attachmentToJson.js
> +        this.logger.debug(`For filename ${fileName} Response status: ${response.status}`);
```suggestion
        this.logger.debug(`For provided filename response status: ${response.status}`);
```

2020-10-26 14:36 UTC, shulkaolka commented on lib/actions/attachmentToJson.js
> +          this.logger.debug(`For filename ${fileName} Result of XML Conversed`);
```suggestion
          this.logger.debug(`Result of XML Conversed`);
```

2020-10-26 14:36 UTC, shulkaolka commented on lib/actions/jsonToXml.js
> +  this.logger.info('Successfully created attachment');
```suggestion
  this.logger.info('Attachment created successfully');
```

2020-10-26 17:45 UTC, A3a3e1 commented on package.json
> +    "elasticio-sailor-nodejs": "2.6.18-dev",
```suggestion
    "elasticio-sailor-nodejs": "2.6.18",
```

2020-10-27 07:52 UTC, denyshld commented on lib/actions/attachmentToJson.js
> +    self.logger.debug('Provided is not .xml file: ', fileName);
done

2020-10-27 07:52 UTC, denyshld commented on lib/actions/attachmentToJson.js
> +        this.logger.debug(`For filename ${fileName} Response status: ${response.status}`);
done

2020-10-27 07:52 UTC, denyshld commented on lib/actions/attachmentToJson.js
> +          this.logger.debug(`For filename ${fileName} Result of XML Conversed`);
done

2020-10-27 07:52 UTC, denyshld commented on lib/actions/jsonToXml.js
> +  this.logger.info('Successfully created attachment');
done

2020-10-27 07:59 UTC, denyshld commented on package.json
> +    "elasticio-sailor-nodejs": "2.6.18-dev",
Done

2020-10-27 14:01 UTC, shulkaolka requested changes
Please, update the following libs to the latest version:
component-commons-library
lodash

2020-10-28 10:48 UTC, shulkaolka approved these changes

2020-10-28 10:55 UTC, A3a3e1 approved these changes

2020-10-29 15:29 UTC, merged